Admin/Manager.WebApp/Controllers/Business/TeacherController.cs
using Manager.DataLayer.Entities;
using Manager.DataLayer.Stores;
using Manager.SharedLibs;
using Manager.SharedLibs.Logging;
using Manager.WebApp.Helpers;
using Manager.WebApp.Models;
using Manager.WebApp.Resources;
using Manager.WebApp.Settings;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Manager.DataLayer.Repositories;
using System.Configuration;
using System.Threading.Tasks;
using Microsoft.AspNet.Identity;
using Manager.WebApp.Caching;
using Manager.DataLayer;
using Microsoft.AspNet.Identity.Owin;

namespace Manager.WebApp.Controllers.Business
{
    public class TeacherController : BaseAuthedController
    {
        private readonly IStoreTeacher _mainStore;
        private readonly IIdentityStore _identityStore;

        private readonly ILog logger = LogProvider.For<TeacherController>();

        public TeacherController(IStoreTeacher mainStore, IIdentityStore identityStore)
        {
            _mainStore = mainStore;

            _identityStore = identityStore;
        }

        public TeacherController(ApplicationUserManager userManager, ApplicationRoleManager roleManager, IIdentityStore identityStore)
        {
            UserManager = userManager;
            RoleManager = roleManager;

            _identityStore = identityStore;
            //Clear cache
            CachingHelpers.ClearUserCache();

        }

        private ApplicationUserManager _userManager;
        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            set
            {
                _userManager = value;
            }
        }

        private ApplicationRoleManager _roleManager;
        public ApplicationRoleManager RoleManager
        {
            get
            {
                return _roleManager ?? HttpContext.GetOwinContext().Get<ApplicationRoleManager>();
            }
            private set
            {
                _roleManager = value;
            }
        }

        /// <summary>
        /// Display list teachers by paging
        /// </summary>
        /// <returns></returns>
        [AccessRoleChecker]
        public ActionResult Index(ManageTeacherModel model)
        {
            int currentPage = 1;
            int pageSize = (model.PageSize != 0 ? model.PageSize : SystemSettings.DefaultPageSize);

            if (Request["Page"] != null)
            {
                currentPage = Utils.ConvertToInt32(Request["Page"], 1);
            }

            var filter = new IdentityTeacher
            {
                Keyword = !string.IsNullOrEmpty(model.Keyword) ? model.Keyword.ToStringNormally() : null,
                Status = model.Status == null ? -1 : (int)model.Status
            };

            try
            {

                var listData = _mainStore.GetByPage(filter, currentPage, pageSize);

                if (listData.HasData())
                {
                    model.SearchResults = new List<IdentityTeacher>();

                    foreach (var item in listData)
                    {
                        // Check cache
                        var info = HelperTeacher.GetBaseInfo(item.Id);
                        if (info != null)
                            model.SearchResults.Add(info);
                    }

                    model.TotalCount = listData[0].TotalCount;
                    model.CurrentPage = currentPage;
                    model.PageSize = pageSize;
                }
            }
            catch (Exception ex)
            {
                this.AddNotification(NotifSettings.Error_SystemBusy, NotificationType.ERROR);

                logger.Error("Failed to get index because: " + ex.ToString());

                return View(model);
            }

            return View(model);
        }

        /// <summary>
        /// Display form create
        /// </summary>
        /// <returns></returns>
        public ActionResult Create()
        {
            var model = new TeacherUpdateModel();

            return View(model);
        }

        /// <summary>
        /// Create Teacher
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult Create(TeacherUpdateModel model)
        {
            var newId = 0;
            try
            {
                //Extract info
                var info = ExtractUpdateData(model);

                //random color
                var random = new Random();
                var color = String.Format("#{0:X6}", random.Next(0x1000000));

                var listTeacher = HelperTeacher.GetList();

                // check Duplicate
                var duplicateColor = listTeacher.Where(x => x.Color == color).FirstOrDefault();

                if (duplicateColor != null && duplicateColor.Id > 0)
                {
                    info.Color = String.Format("#{0:X6}", random.Next(0x1000000));
                }

                info.Color = color;

                // Insert Teacher
                newId = _mainStore.Insert(info);

                //Clear Cache List
                HelperTeacher.ClearCache(0);

                if (newId > 0)
                {
                    this.AddNotification(ManagerResource.LB_INSERT_SUCCESS, NotificationType.SUCCESS);
                }
                else
                {
                    this.AddNotification(NotifSettings.Error_SystemBusy, NotificationType.ERROR);
                }
            }
            catch (Exception ex)
            {
                this.AddNotification(NotifSettings.Error_SystemBusy, NotificationType.ERROR);

                logger.Error("Failed for Create Teacher request: " + ex.ToString());

                return View(model);
            }

            return RedirectToAction("Index");
        }

        /// <summary>
        /// Display Form Edit
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [AccessRoleChecker]
        public ActionResult Edit(int id)
        {
            /*var model = new TeacherUpdateModel();
            try
            {
                var infoTeacher = HelperTeacher.GetBaseInfo(id);


                var agencyId = GetCurrentAgencyId();
                if (string.IsNullOrEmpty(infoTeacher.UserId))
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest, "User id was not provided");
                }

                var allRoles = new RoleRepository().GetRoleByAgencyId(agencyId);


                var applicationUser = new RpsUser().GetById(id);
                if (applicationUser == null)
                {
                    return RedirectToErrorPage();
                }

                model.Lockout = new LockoutViewModel();
                var isLocked = applicationUser.LockoutEnabled;
                model.Lockout.Status = isLocked ? LockoutStatus.Locked : LockoutStatus.Unlocked;
                model.IsActived = !isLocked;
                if (model.Lockout.Status == LockoutStatus.Locked)
                {
                    model.Lockout.LockoutEndDate = (await UserManager.GetLockoutEndDateAsync(applicationUser.Id)).DateTime;
                }

                model.UserName = applicationUser.UserName;

                var userRoles = new RoleRepository().GetRoleByUserId(applicationUser.Id);
                var hasRoles = userRoles.HasData();

                model.RolesList = new List<SelectItem>();
                if (allRoles.HasData())
                {
                    foreach (var r in allRoles)
                    {
                        var item = new SelectListItem();
                        item.Text = r.Name;
                        item.Value = r.Id;
                        if (hasRoles)
                        {
                            item.Selected = userRoles.Exists(x => x.Id == r.Id);
                            if (item.Selected)
                                model.Role = r.Id;
                        }

                        model.RolesList.Add(item);
                    }
                }

                model.SEmail = Request["Email"];
                model.SRoleId = Request["RoleId"];
                model.SearchExec = Request["SearchExec"];
                model.Page = Request["Page"];
                model.SIsLocked = Convert.ToInt32(Request["IsLocked"]);

                return View(model);
            }
            catch (Exception ex)
            {
                logger.ErrorFormat("Could not display EditUser page because: {0}", ex.ToString());

                return RedirectToErrorPage();
            }*/

            if (id == 0)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            try
            {
                // Check cache 

                var info = HelperTeacher.GetBaseInfo(id);

                if (info == null)
                    return RedirectToErrorPage();
                //Render to view model
                var model = ParseUpdateDataForm(info);

                return View(model);
            }
            catch (Exception ex)
            {
                this.AddNotification(NotifSettings.Error_SystemBusy, NotificationType.ERROR);

                logger.Error("Failed get Edit Teacher because: " + ex.ToString());
            }

            return View(new TeacherUpdateModel());
        }

        /// <summary>
        /// Edit Teacher
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult Edit(TeacherUpdateModel model)
        {
            try
            {
                //Extract data
                var info = ExtractUpdateData(model);

                // Update Teacher

Admin/Manager.WebApp/Views/Teacher/Create.cshtml
@model Manager.WebApp.Models.TeacherUpdateModel

@{
    ViewBag.Title = "先生追加";
}

@Html.Partial("_Notifications")
<div class="row">
    <div class="col-lg-12">
        <!--begin::Portlet-->
        <div class="m-portlet">
            <div class="m-portlet__head">
                <div class="m-portlet__head-caption">
                    <div class="m-portlet__head-title">
                        <span class="m-portlet__head-icon">
                            <i class="fa fa-plus text-info"></i>
                        </span>
                        <h3 class="m-portlet__head-text">
                            @ViewBag.Title
                        </h3>
                    </div>
                </div>
            </div>
            <!--begin::Form-->
            @using (Html.BeginForm("Create", "Teacher", FormMethod.Post, new { @class = "m-form m-form--fit", role = "form", autocomplete ="off" }))
            {
                @Html.Partial("_UpdateForm", Model)
            }
        </div>
        <!--end::Portlet-->
    </div>
</div>

Admin/Manager.WebApp/Views/Teacher/Edit.cshtml
@using Manager.WebApp.Resources
@model Manager.WebApp.Models.TeacherUpdateModel

@{
    ViewBag.Title = "先生編集";
}

@Html.Partial("_Notifications")

@Html.Partial("../Widgets/Modals/_DefaultModal")

<div class="row">
    <div class="col-lg-12">
        <!--begin::Portlet-->
        <div class="m-portlet">
            <div class="m-portlet__head">
                <div class="m-portlet__head-caption">
                    <div class="m-portlet__head-title">
                        <span class="m-portlet__head-icon">
                            <i class="fa fa-edit text-info"></i>
                        </span>
                        <h3 class="m-portlet__head-text">
                            @ViewBag.Title
                        </h3>
                    </div>
                </div>
            </div>
            <!--begin::Form-->
            @using (Html.BeginForm("Edit", "Teacher", FormMethod.Post, new { @class = "m-form m-form--fit", role = "form" }))
            {
                @Html.Partial("_UpdateForm", Model)}
            <!--end::Form-->
        </div>
        <!--end::Portlet-->
    </div>
</div>

Admin/Manager.WebApp/Views/Teacher/Index.cshtml
@model Manager.WebApp.Models.ManageTeacherModel

@Html.Partial("_Notifications")

@Html.Partial("../Widgets/Modals/_DefaultModal")

@{
    ViewBag.Title = "先生リスト";
}

<div class="m-portlet" m-portlet="true" id="FormSearchTool">
    <div class="m-portlet__head">
        <div class="m-portlet__head-caption">
            <div class="m-portlet__head-title">
                <span class="m-portlet__head-icon">
                    <i class="fa fa-search"></i>
                </span>
                <h3 class="m-portlet__head-text">
                    検索
                </h3>
            </div>
        </div>
        <div class="m-portlet__head-tools">
            <ul class="m-portlet__nav">
                <li class="m-portlet__nav-item">
                    <a href="javascript:;" m-portlet-tool="toggle" class="m-portlet__nav-link m-portlet__nav-link--icon">
                        <i class="la la-angle-down"></i>
                    </a>
                </li>
            </ul>
        </div>
    </div>
    @Html.Partial("_SearchForm", Model)
</div>

<div class="m-portlet">
    <div class="m-portlet__head">
        <div class="m-portlet__head-caption">
            <div class="m-portlet__head-title">
                <span class="m-portlet__head-icon">
                    <i class="fa fa-list-alt" style="color:#1A3365 !important"></i>
                </span>
                <h3 class="m-portlet__head-text">
                    @ViewBag.Title
                </h3>
            </div>
        </div>
    </div>
    <div class="m-portlet__body">
        <div class="row mb10">
            <div class="col-xl-1 col-sm-2 col-3">
                <form action="/Teacher" method="get" class="m-form m-form--fit" id="form-pagesize">
                    <input type="hidden" name="Keyword" value="@(Model.Keyword)" />
                    <select id="pagesize" name="PageSize" class="form-control form-control-sm">
                        <option value="5" @(Model.PageSize == 5 ? "selected" : "")>5</option>
                        <option value="10" @(Model.PageSize == 10 ? "selected" : "")>10</option>
                        <option value="20" @(Model.PageSize == 20 ? "selected" : "")>20</option>
                        <option value="30" @(Model.PageSize == 30 ? "selected" : "")>30</option>
                    </select>
                </form>
            </div>
            <div class="col-xl-11 col-sm-10 col-9 text-right">
                <a class="btn btn-white btn-sm btn-info" href="/Teacher/Create">
                    <i class="fa fa-plus"></i> 追加
                </a>
            </div>
        </div>
        <div class="m-section">
            <div class="m-section__content">
                <table class="table m-table table-bordered table-hover m-table--border-metal table-responsive-xl">
                    <thead>
                        <tr>
                            <th class="text-center" width="50">#</th>
                            <th class="text-center">氏名</th>
                            <th class="text-center" width="150">生年月日</th>
                            <th class="text-center" width="150">性別</th>
                            <th class="text-center">メールアドレス</th>
                            <th class="text-center" width="200">電話番号</th>
                            <th class="text-center" width="150">Action</th>
                        </tr>
                    </thead>
                    <tbody class="text-nowrap">
                        @if (Model.SearchResults != null && Model.SearchResults.Count > 0)
                        {
                            var stt = 0;
                            foreach (var record in Model.SearchResults)
                            {
                                stt++;

                                <tr>
                                    <td class="text-center">@(stt + (Model.CurrentPage - 1) * Model.PageSize) </td>
                                    <td>
                                        @record.Name
                                    </td>
                                    <td class="text-center">@(record.DateBirth != null ? record.DateBirth.Value.ToString("dd/MM/yyyy") : null)</td>
                                    <td>
                                        @{
                                            var gender = string.Empty;

                                            if (record.Gender == (int)EnumGender.Famale)
                                            {
                                                gender = "男";
                                            }
                                            if (record.Gender == (int)EnumGender.Male)
                                            {
                                                gender = "女";
                                            }
                                        }
                                        @gender
                                    </td>
                                    <td>@record.Email</td>
                                    <td>@record.Phone</td>
                                    <td class="text-center">
                                        <div class="dropdown">
                                            <a href="javascript;" class="btn m-btn m-btn--hover-warning m-btn--icon m-btn--icon-only m-btn--pill" data-toggle="dropdown">
                                                <i class="la la-ellipsis-h"></i>
                                            </a>
                                            <div class="dropdown-menu dropdown-menu-right">
                                               @* <a class="dropdown-item btn m-btn m-btn--hover-warning" data-href="" data-modal="" data-size="default">
                                                    <i class="fa fa-eye"></i> Chi tiết
                                                </a>*@
                                                <a class="dropdown-item btn m-btn m-btn--hover-warning" href="@Url.Action("Edit", "Teacher", new { id = record.Id})" data-size="default">
                                                    <i class="fa fa-pencil-square-o"></i> 編集
                                                </a>
                                                <a class="dropdown-item btn m-btn m-btn--hover-warning" href="javascript" data-href="@Url.Action("Delete", "Teacher", new { id = record.Id })" data-modal="" data-size="default">
                                                    <i class="la la-trash"></i> 削除
                                                </a>
                                            </div>
                                        </div>
                                    </td>
                                </tr>

                            }
                        }
                        else
                        {

                            <tr>
                                <td colspan="11">
                                    レコードがありません
                                </td>
                            </tr>
                        }

                    </tbody>
                </table>
            </div>
            @RenderPaging()

        </div>
    </div>
</div>

@helper RenderPaging()
{

    <div class="m_datatable m-datatable m-datatable--default m-datatable--brand m-datatable--loaded">
        <div class="m-datatable__pager m-datatable--paging-loaded clearfix">
            @if (Model.WasOverRecordsInPage())
            {

                @Html.BootstrapPager(Model.CurrentPage, index => Url.Action("Index", "Teacher",
                     new
                     {
                         Page = index,
                         Keyword = Model.Keyword,
                         PageSize = Model.PageSize
                     }),
                     Model.TotalCount, pageSize: Model.PageSize, numberOfLinks: 10)}

            @if (Model.TotalCount > 0)
            {

                <div class="m-datatable__pager-info">
                    <span class="m-datatable__pager-detail">
                        全 @Model.TotalCount レコード @Model.StartCount() 〜 @Model.EndCount(Model.SearchResults.Count())件を表示中
                    </span>
                </div>}

        </div>
    </div>
}

@section PageInlineStyles
    {
    <style>
        .table-hover tbody tr:hover {
            background-color: #f0f0f0 !important;
        }

        .m-table.m-table--border-metal, .m-table.m-table--border-metal td, .m-table.m-table--border-metal th {
            border-color: #5759622b;
        }
    </style>
}

@section PageInlineScripts
 {
    <script>
        $(document).ready(function () {
            $('#pagesize').on('change', function () {
                $('#form-pagesize').submit();
            })
        });
    </script>
}

Admin/Manager.WebApp/Views/Teacher/_PopupDelete.cshtml
@model int

<div class="modal-header">
    <h5 class="modal-title" id="">
        削除してもよろしいでしょうか！
    </h5>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">
            &times;
        </span>
    </button>
</div>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <input type="hidden" name="Id" value="@Model" />

    <div class="modal-footer">
        <button type="submit" class="btn btn-info btn-sm">
            <i class="fa fa-trash"></i> 削除
        </button>
        <button type="button" class="btn btn-secondary btn-sm" data-dismiss="modal">
            <i class="fa fa-remove"></i> キャンセル
        </button>
    </div>
}

Admin/Manager.WebApp/Views/Teacher/_SearchForm.cshtml
@model Manager.WebApp.Models.ManageTeacherModel

<style>
    .tooltip-inner {
        display: none;
    }
</style>

<form action="/Teacher" method="get" class="m-form m-form--fit">
    <div class="m-portlet__body">
        <div class="form-group row">
            <div class="col-md-6">
                <input type="hidden" name="PageSize" value="@Model.PageSize" />
                @Html.TextBoxFor(m => m.Keyword, new { @class = "form-control form-control-sm m-input", placeholder = "先生の名前を入力してください" })
            </div>
            <div class="col-md-6">
                <button type="submit" class="btn btn-info btn-sm">
                    <i class="fa fa-search"></i> 検索
                </button>
            </div>
        </div>
    </div>
</form>

Admin/Manager.WebApp/Views/Teacher/_UpdateForm.cshtml
@using Manager.WebApp.Resources
@model Manager.WebApp.Models.TeacherUpdateModel

@Html.AntiForgeryToken()

@{
    var dateBirth = Model.DateBirth != null ? Model.DateBirth.Value.ToString("yyyy-MM-dd") : null;
}

<div class="m-portlet__body">
    <div class="form-group m-form__group row">
        <div class="col-xl-4 col-sm-6">
            <label class="form-control-label">
                氏名 <span class="m--font-danger"> * </span>:
            </label>
            @Html.TextBoxFor(m => m.Name, new { @class = "form-control m-input", placeholder = "名前を入力してください" })
            @Html.ValidationMessageFor(m => m.Name, "", new { @class = "text-danger" })
        </div>
        
    </div>

    <div class="form-group m-form__group row">
        <div class="col-xl-4 col-sm-6">
            <label class="form-control-label">
                電話番号:
            </label>
            @Html.TextBoxFor(m => m.Phone, new { @class = "form-control m-input", @type = "text", placeholder = "電話番号を入力してください", autocomplete = "off" })
            @Html.ValidationMessageFor(m => m.Phone, "", new { @class = "text-danger" })
        </div>
        <div class="col-xl-4 col-sm-6">
            <label class="form-control-label">
                メールアドレス <span class="m--font-danger"> * </span>:
            </label>
            @Html.TextBoxFor(m => m.Email, new { @class = "form-control m-input", @type = "email", placeholder = "メールアドレスを入力してください" })
            @Html.ValidationMessageFor(m => m.Email, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group m-form__group row">
        <div class="col-xl-8 col-sm-6">
            <label class="form-control-label">
                住所:
            </label>
            @Html.TextBoxFor(m => m.Address, new { @class = "form-control m-input" })
            @Html.ValidationMessageFor(m => m.Address, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group m-form__group row">
        <div class="col-xl-4 col-sm-6">
            <label class="form-control-label">
                生年月日:
            </label>
            <div class="row">
                <div class="col-sm-6">
                    @Html.TextBoxFor(m => m.DateBirth, new { @class = "form-control m-input", Type = "date", Value = dateBirth })
                </div>
            </div>
        </div>
        <div class="col-xl-4 col-sm-6">
            <label class="form-control-label">
                性別:
            </label>
            <div class="m-radio-inline">
                <label class="m-radio m-radio--check-bold m-radio--state-success">
                    <input type="radio" checked name="Gender" value="1" @(Model.Gender == (int)EnumGender.Famale ? "checked" : string.Empty)>
                    男
                    <span></span>
                </label>
                <label class="m-radio m-radio--check-bold m-radio--state-success">
                    <input type="radio" name="Gender" value="2" @(Model.Gender == (int)EnumGender.Male ? "checked" : string.Empty)>
                    女
                    <span></span>
                </label>
            </div>
        </div>
    </div>
    @*<div class="form-group m-form__group row">
        <div class="col-xl-12">
            <fieldset class="pb20">
                <legend class="legend-ctrl">
                    アカウント作成 <i class="fa fa-angle-up"></i>
                </legend>

                <div class="fieldset-content" style="">
                    <div class="row">
                        <div class="col-xl-4 form-group">
                            @Html.LabelFor(m => m.UserName, new { @class = "form-control-label" }) <span class="required-input">*</span>
                            @Html.TextBoxFor(m => m.UserName, new { @class = "form-control form-control-warning m-input", autocomplete = "new-password" })
                            @Html.ValidationMessageFor(m => m.UserName, "", new { @class = "text-danger" })
                        </div>
                        <div class="col-xl-4 form-group">
                            <label for="">
                                @ManagerResource.LB_ROLES_ASSIGNED:
                            </label>
                            <div class="m-radio-inline">
                                @if (Model != null && Model.RolesList != null && Model.RolesList.Count() > 0)
                                {
                                    foreach (var item in Model.RolesList)
                                    {
                                        <label class="m-radio">
                                            <input type="radio" name="Role" value="@item.Value">
                                            @item.Text
                                            <span></span>
                                        </label>
                                    }
                                }
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-xl-4 form-group">
                            @Html.LabelFor(m => m.Password, new { @class = "form-control-label" }) <span class="required-input">*</span>
                            @Html.PasswordFor(m => m.Password, new { @class = "form-control form-control-warning m-input" })
                            @Html.ValidationMessageFor(m => m.Password, "", new { @class = "text-danger" })
                        </div>
                        <div class="col-xl-4 form-group">
                            @Html.LabelFor(m => m.ConfirmPassword, new { @class = "form-control-label" })
                            @Html.PasswordFor(m => m.ConfirmPassword, new { @class = "form-control form-control-warning m-input" })
                            @Html.ValidationMessageFor(m => m.ConfirmPassword, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
            </fieldset>
        </div>

    </div>*@
</div>

<div class="m-portlet__foot m-portlet__foot--fit">
    <div class="m-form__actions">
        <div class="row">
            <div class="col-12 text-left">
                <button type="submit" class="btn btn-sm btn-info">
                    <i class="fa fa-check"></i>
                    保存
                </button>
                <a type="reset" class="btn btn-sm btn-secondary" href="@Url.Action("Index", "Teacher")">
                    <i class="fa fa-mail-reply"></i>
                    戻る
                </a>
            </div>
        </div>
    </div>
</div>